# Generated by Django 5.1.7 on 2026-04-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='submitted_by',
            field=models.CharField(blank=True, default='', help_text='Your name (optional)', max_length=100),
        ),
    ]
